config/routes.rb
Rails.application.routes.draw do
  root "redes#index"
  resources :redes do
    resources :registros
  end

  # Escrever por GET
  get "redes/:rede_id/registros/:id/:valor" => "registros#update_simplificado", :constraints => { :valor => /[^\/]+/ }

  # Modo resumido
  get "t/:rede_id/r/:id/:valor" => "registros#update_simplificado", :constraints => { :valor => /[^\/]+/ }
  get "t/:rede_id/r/:id" => "registros#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/rede.rb
class Rede < ApplicationRecord
  has_secure_token
  has_many :registros, dependent: :destroy

  #faz path helpers como edit_rede_path apontarem para o caminho /redes/:token
  def to_param
    token
  end
end

app/models/registro.rb
class Registro < ApplicationRecord
  belongs_to :rede
  enum tipo: [ :int, :float, :string, :boolean ]

  def to_param
    nome
  end

  def self.criar nome, v, rede
    case v.class
    when Integer
      rede.registros.create! tipo: :int, valor: v.to_s, nome:
    when Float
      rede.registros.create! tipo: :float, valor: v.to_s, nome:
    when String
      rede.registros.create! tipo: :string, valor: v, nome:
    when TrueClass, FalseClass
      rede.registros.create! tipo: :boolean, valor: v.to_s, nome:
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :allow_cross_domain_access
  after_action :cors_set_access_control_headers
  
  def allow_cross_domain_access
      headers['Access-Control-Allow-Origin'] = '*'# http://localhost:9000
      headers['Access-Control-Allow-Headers'] = 'GET, POST, PUT, DELETE, OPTIONS'
      headers['Access-Control-Allow-Methods'] = %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(',')
      headers['Access-Control-Max-Age'] = '1728000'
  end
  def cors_set_access_control_headers
          headers['Access-Control-Allow-Origin'] = '*'
          headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
          headers['Access-Control-Allow-Headers'] = %w{Origin Accept Content-Type X-Requested-With X-CSRF-Token}.join(',')
          headers['Access-Control-Max-Age'] = "1728000"
  end
end

app/controllers/redes_controller.rb
class RedesController < ApplicationController
  before_action :set_rede, only: %i[ show edit update destroy ]

  # GET /redes or /redes.json
  def index
    @redes = Rede.all
  end

  # GET /redes/1 or /redes/1.json
  def show
    @registros = @rede.registros.limit 100
  end

  # GET /redes/new
  def new
    @rede = Rede.new
  end

  # GET /redes/1/edit
  def edit
  end

  # POST /redes or /redes.json
  def create
    @rede = Rede.new(rede_params)

    respond_to do |format|
      if @rede.save
        format.html { redirect_to rede_url(@rede), notice: "Rede criada." }
        format.json { render :show, status: :created, location: @rede }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rede.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redes/1 or /redes/1.json
  def update
    respond_to do |format|
      if @rede.update(rede_params)
        format.html { redirect_to rede_url(@rede), notice: "Rede salva." }
        format.json { render :show, status: :ok, location: @rede }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rede.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redes/1 or /redes/1.json
  def destroy
    @rede.destroy

    respond_to do |format|
      format.html { redirect_to redes_url, notice: "Rede excluida." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rede
      @rede = Rede.find_by_token(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rede_params
      params.require(:rede).permit(:nome, :token)
    end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
  before_action :set_rede, only: %i[ show edit update destroy update_simplificado ]

  # GET /redes or /redes.json
  def index
    @registros = @rede.registros.limit 100
  end

  # GET /redes/1 or /redes/1.json
  def show
    @registro = @rede.registros.find_by_nome(params[:id])
    if @registro
      render formats: :text
    else
      render plain: "Registro não encontrado"
    end
  end

  # GET /redes/:token/registros/:nome/:valor
  def update_simplificado
    @registro = @rede.registros.find_by_nome(params[:id])
    if @registro
      @registro.update(valor: params[:valor])
    else
      @rede.registros.create(nome: params[:id], valor: params[:valor], tipo: 'string')
    end
    render plain: "OK"
  end


  # GET /redes/new
  def new
    @registro = @rede.registros.new
  end

  # GET /redes/1/edit
  def edit
  end

  # POST /redes or /redes.json
  def create
    @registro = @rede.registros.new(registro_params)

    respond_to do |format|
      if @registro.save
        format.html { redirect_to rede_url(@rede), notice: "Registro criado." }
        format.json { render :show, status: :created, location: @registro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redes/1 or /redes/1.json
  def update
    respond_to do |format|
      if @registro.update(registro_params)
        format.html { redirect_to rede_url(@rede), notice: "Registro atualizado." }
        format.json { render :show, status: :ok, location: @registro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @registro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redes/1 or /redes/1.json
  def destroy
    @registro.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rede
      @rede = Rede.find_by_token(params[:rede_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def registro_params
      params.require(:registro).permit(:nome, :valor, :tipo)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/redes_helper.rb
module RedesHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
  def valor_com_tipo registro
    case registro.tipo
    when "int"
      content_tag :span, registro.valor.to_i, class: ""
    when "float"
      content_tag :span, registro.valor.to_f, class: ""
    when "string"
      content_tag :span, registro.valor.inspect, class: "font-medium"
    when "boolean"
      if registro.valor == "true"
        content_tag :span, "true", class: "text-green-900"
      else
        content_tag :span, "false", class: "text-red-900"
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IDC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/redes/_form.html.erb
<%= form_with(model: rede, class: "contents") do |form| %>
  <% if rede.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(rede.errors.count, "error") %> prohibited this rede from being saved:</h2>

      <ul>
        <% rede.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :nome %>
    <%= form.text_field :nome, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% if rede.token %>
  <p class="my-5">
    <strong class="block font-medium mb-1">Token:</strong>
    <%= rede.token %>
  </p>
  <% end %>


  <div class="inline">
    <%= form.submit "Salvar Rede", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/redes/_rede.html.erb
<div id="<%= dom_id rede %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Nome:</strong>
    <%= rede.nome %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Token:</strong>
    <%= rede.token %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Abrir", rede, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Editar', edit_rede_path(rede), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/redes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editar rede</h1>

  <%= render "form", rede: @rede %>

  <%= link_to "Abir", @rede, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Voltar", redes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/redes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Redes</h1>
    <%= link_to 'Nova Rede', new_rede_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="redes" class="min-w-full">
    <%= render @redes %>
  </div>
</div>

app/views/redes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Nova Rede</h1>

  <%= render "form", rede: @rede %>

  <%= link_to 'Voltar', redes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/redes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <h1 class="font-bold text-4xl">Rede: <%= @rede.nome %></h1>
    <p><%= @rede.token %></p>
    <%= link_to 'Editar', edit_rede_path(@rede), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Apagar', rede_path(@rede), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Voltar', redes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>

    <div class="mx-auto mt-10">
  <h1 class="font-bold text-4xl">Registros</h1>
  <% @registros.each do |registro| %>
    <%= render partial: 'registros/registro', locals: { registro: registro } %>
  <% end %>
</div>
  </div>

</div>

app/views/registros/_registro.html.erb
<p><%= "#{registro.nome}: " %> <%=valor_com_tipo registro %></p>

app/views/registros/show.text.erb
<%= @registro.valor %>